/**
 * @file schema_v3_market.sql
 * @description Phase 5 schema migration: P2P marketplace (market_listings table).
 *
 * ================================================================
 * WHY A SEPARATE TABLE FOR MARKET LISTINGS?
 * ================================================================
 *
 * A marketplace listing represents a DIFFERENT concept from inventory:
 *
 *   - inventories: "how much of resource X does player Y currently hold?"
 *   - market_listings: "player Y has offered N units of X for sale at price P."
 *
 * These are distinct entities. The listing has its own lifecycle (ACTIVE → SOLD
 * or ACTIVE → CANCELLED), its own price metadata, and a temporal history we
 * want to preserve (who sold what, when, for how much).
 *
 * ================================================================
 * ESCROW MODEL — How resources are held during a listing
 * ================================================================
 *
 * When a player creates a listing, the listed resources are immediately
 * DEDUCTED from their `inventories` row. This is the "escrow" step:
 *
 *   Before listing: player has 20 LIGNUM in inventories.
 *   POST /market/p2p/list { resource_id: 'LIGNUM', amount: 10, price_per_unit: 5 }
 *   After listing:  player has 10 LIGNUM in inventories + 1 row in market_listings.
 *
 * The 10 LIGNUM listed is NOT in the player's accessible inventory during
 * the listing's lifetime. It is "locked" by the market listing record itself.
 *
 * When the listing is BOUGHT:
 *   - The buyer's Sestertius is deducted.
 *   - The 10 LIGNUM is transferred to the buyer (added to buyer's inventories).
 *   - The seller receives the Sestertius payment.
 *   - The listing row is marked as 'SOLD'.
 *
 * This escrow model prevents a player from:
 *   a) Listing resources they don't have.
 *   b) Spending the same resources twice (listing + NPC sell simultaneously).
 *   c) Withdrawing the resources while the listing is active.
 *
 * ================================================================
 * INTEGER-ONLY CURRENCY (No floating-point)
 * ================================================================
 *
 * Both `amount` and `price_per_unit` are stored as INT (INTEGER in PostgreSQL).
 * The total price of a listing is always:
 *
 *   total_price = amount (INT) * price_per_unit (INT) = INT
 *
 * Integer multiplication of two integers always produces an integer.
 * There is NO floating-point arithmetic anywhere in the Sestertius economy.
 * This eliminates an entire class of bugs (rounding errors, imprecise comparisons)
 * that plague games which store prices as FLOAT or DECIMAL.
 *
 * Rule: Sestertius amounts are ALWAYS stored and computed as integers.
 *
 * ================================================================
 * RUN THIS FILE TO APPLY THE MIGRATION
 * ================================================================
 *
 * Connect to your database and run:
 *   psql -U postgres -d opes_db -f backend/src/db/schema_v3_market.sql
 *
 * Or using the psql interactive shell:
 *   \i backend/src/db/schema_v3_market.sql
 *
 * This file is idempotent (IF NOT EXISTS) — safe to run multiple times.
 */

-- ================================================================
-- TABLE: market_listings
-- ================================================================

CREATE TABLE IF NOT EXISTS market_listings (
  /**
   * UUID primary key, generated by PostgreSQL.
   * UUIDs prevent sequential enumeration attacks: an attacker cannot
   * guess listing IDs by incrementing a number (1, 2, 3...) — they
   * would need to know the full 128-bit UUID.
   */
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  /**
   * The player who created this listing (the seller).
   *
   * ON DELETE CASCADE: if a user account is deleted, all their listings
   * are automatically removed. This prevents orphaned listings pointing
   * to non-existent users, which would cause JOIN errors in the market query.
   *
   * We do NOT expose seller_id in the public market API — only the seller's
   * username is returned, preventing enumeration of user IDs.
   */
  seller_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  /**
   * The resource being sold (e.g., 'LIGNUM', 'FRUMENTUM').
   * Matches the resource_id values used in the inventories table.
   * VARCHAR(50) is consistent with the inventories table definition.
   */
  resource_id    VARCHAR(50) NOT NULL,

  /**
   * How many units of the resource are listed for sale.
   *
   * CHECK (amount > 0): it is nonsensical to list 0 or negative units.
   * This constraint is enforced at the database level regardless of
   * what the application code does — defense in depth.
   */
  amount         INT         NOT NULL,
  CONSTRAINT market_listings_amount_positive CHECK (amount > 0),

  /**
   * The seller's asking price per single unit, in Sestertius.
   *
   * IMPORTANT: This is stored as INT (not FLOAT, not DECIMAL).
   * Sestertius is an indivisible integer currency. Floating-point
   * prices would introduce rounding errors in total_price calculations.
   *
   * CHECK (price_per_unit > 0): listings must have a positive price.
   * A listing at 0 Sestertius would let buyers take resources for free,
   * which might be intentional gifting — but we restrict it for now.
   */
  price_per_unit INT         NOT NULL,
  CONSTRAINT market_listings_price_positive CHECK (price_per_unit > 0),

  /**
   * The lifecycle state of this listing.
   *
   * State machine:
   *   ACTIVE   → Initial state. Listing is visible and purchasable.
   *   SOLD     → Listing was successfully purchased. Resources transferred to buyer.
   *   CANCELLED → (Future feature) Seller cancelled the listing. Resources returned.
   *
   * We use a VARCHAR CHECK constraint rather than a PostgreSQL ENUM because
   * CHECK constraints can be altered without a table rewrite. Adding a new state
   * (e.g., 'EXPIRED') only requires an ALTER TABLE to update the CHECK constraint,
   * whereas ENUMs require a new type definition and cannot be removed cleanly.
   */
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT market_listings_status_valid CHECK (status IN ('ACTIVE', 'SOLD', 'CANCELLED')),

  /**
   * When the listing was created. Stored as TIMESTAMPTZ (with timezone) for
   * correctness across different server/client timezones.
   * Used for ORDER BY in the market feed (newest listings first).
   */
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================================================================
-- INDEXES
-- ================================================================

/**
 * Index on seller_id — supports "fetch all listings by this player" queries.
 * Used when a player wants to view and manage their own active listings.
 * Without this index, the query would perform a full table scan for every
 * player, which degrades as the number of listings grows.
 */
CREATE INDEX IF NOT EXISTS idx_market_listings_seller_id
  ON market_listings(seller_id);

/**
 * Index on status — supports the primary read query: "fetch all ACTIVE listings".
 * The market feed runs this query on every page load for every player.
 *
 * Most listings will eventually become 'SOLD'. Without this index, fetching
 * ACTIVE listings requires scanning all SOLD listings too, which is wasteful.
 *
 * With this index, PostgreSQL can jump directly to the ACTIVE rows.
 *
 * SCALABILITY: For a high-volume market with millions of listings, a partial
 * index would be even more efficient:
 *   CREATE INDEX ... ON market_listings(created_at) WHERE status = 'ACTIVE'
 * This indexes only the rows we actually query, dramatically reducing index size.
 * This optimization can be applied later when traffic warrants it.
 */
CREATE INDEX IF NOT EXISTS idx_market_listings_status
  ON market_listings(status);
